version: '3'

networks:
  mfcsafe_crud:

services:
  postgres:
    # TypeORM fails with Postgres v.12
    image: postgres:11.5
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mfcsafe_crud
    networks:
      - mfcsafe_crud

  mysql:
    image: mysql:5.7
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: mfcsafe_crud
      MYSQL_USER: mfcsafe_crud
      MYSQL_PASSWORD: mfcsafe_crud
      MYSQL_ROOT_PASSWORD: mfcsafe_crud

  redis:
    image: redis:alpine
    ports:
      - 6399:6379
    command: redis-server
    networks:
      - mfcsafe_crud

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mfcsafe_crud
