export const FEAUTURE_NAME_METADATA = 'mfc_FEAUTURE_NAME_METADATA';
export const ACTION_NAME_METADATA = 'mfc_ACTION_NAME_METADATA';
export const OVERRIDE_METHOD_METADATA = 'mfc_OVERRIDE_METHOD_METADATA';
export const PARSED_BODY_METADATA = 'mfc_PARSED_BODY_METADATA';
export const PARSED_CRUD_REQUEST_KEY = 'mfc_PARSED_CRUD_REQUEST_KEY';
export const CRUD_OPTIONS_METADATA = 'mfc_CRUD_OPTIONS_METADATA';
export const CRUD_AUTH_OPTIONS_METADATA = 'mfc_CRUD_AUTH_OPTIONS_METADATA';
