export const FEAUTURE_NAME_METADATA = 'mfcsafe_FEAUTURE_NAME_METADATA';
export const ACTION_NAME_METADATA = 'mfcsafe_ACTION_NAME_METADATA';
export const OVERRIDE_METHOD_METADATA = 'mfcsafe_OVERRIDE_METHOD_METADATA';
export const PARSED_BODY_METADATA = 'mfcsafe_PARSED_BODY_METADATA';
export const PARSED_CRUD_REQUEST_KEY = 'mfcsafe_PARSED_CRUD_REQUEST_KEY';
export const CRUD_OPTIONS_METADATA = 'mfcsafe_CRUD_OPTIONS_METADATA';
export const CRUD_AUTH_OPTIONS_METADATA = 'mfcsafe_CRUD_AUTH_OPTIONS_METADATA';
